# Scaffolding generated by Casein v5.1.1.5

module Casein
  class ContactFormsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Contact forms'
  		@contact_forms = ContactForm.order(sort_order(:first_name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View contact form'
      @contact_form = ContactForm.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new contact form'
    	@contact_form = ContactForm.new
    end

    def create
      @contact_form = ContactForm.new contact_form_params
    
      if @contact_form.save
        flash[:notice] = 'Contact form created'
        redirect_to casein_contact_forms_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new contact form'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update contact form'
      
      @contact_form = ContactForm.find params[:id]
    
      if @contact_form.update_attributes contact_form_params
        flash[:notice] = 'Contact form has been updated'
        redirect_to casein_contact_forms_path
      else
        flash.now[:warning] = 'There were problems when trying to update this contact form'
        render :action => :show
      end
    end
 
    def destroy
      @contact_form = ContactForm.find params[:id]

      @contact_form.destroy
      flash[:notice] = 'Contact form has been deleted'
      redirect_to casein_contact_forms_path
    end
  
    private
      
      def contact_form_params
        params.require(:contact_form).permit(:first_name, :last_name, :business_name, :email, :phone, :details)
      end

  end
end